### ISSUE TITLE
The problem with the end of the process when working with big data .

### ISSUE THREAD

**Issue by andrydl** [reorg/pg_repack#86] opened 2016-07-01 13:58 UTC
The process pg_repack is not completed until the work previously running transactions. Even if they are not related to repacking tables. If before pg_repack starting "autovacuum analyze" another table, it wait ending "autovacuum analyze". But if the table has a size several terabytes ,  then the wait will be very long (several days). In pg_stat_activity row  "SELECT pid FROM pg_locks  WHERE locktype = 'virtualxid' AND pid <> pg_backend_pid()  AND virtualtransaction = ANY($1) " or "SELECT repack.repack_apply($1, $2, $3, $4, $5, $6)". I think it's wrong to wait for the completion of all previously started transaction.Moreover, they are not related to the processed table.

**Comment by schmiddy** [comment] 2016-07-02 09:26
Yeah, this is a duplicate of #26 .

**Closed by schmiddy** 2016-07-02 09:26 UTC
