### ISSUE TITLE
Re-enable PostgreSQL 9.6 testing on Travis

### ISSUE THREAD

**Issue by dvarrazzo** [reorg/pg_repack#250] opened 2020-10-01 19:48 UTC
Testing on PostgreSQL 9.6 was disabled because failing for reasons unrelated to pg_repack (see 66d7426f and [travis job](https://travis-ci.org/github/reorg/pg_repack/jobs/731695983)).

@df7cb has a more reliable way to deploy Postgres versions on Travis: see suggestions in #246

**Comment by MichaelDBA** [comment] 2023-03-15 12:12
Why support EOL'd versions of Postgres?

**Comment by dvarrazzo** [comment] 2023-03-17 17:16
No reason, really. At the time of writing this 9.6 was probably not EOL'd yet.

**Comment by za-arthur** [comment] 2024-02-03 23:47
I guess we can close this issue, since there are tests on Travis anymore. Tests were moved to Github actions
https://github.com/reorg/pg_repack/blob/624745b4bf7df34ae614632c6d8d47da4a26eb1c/.github/workflows/regression.yml#L17
which also supports PostgreSQL 9.6.

Closing this issue for now. Feel free to re-open it.

**Closed by za-arthur** 2024-02-03 23:47 UTC
Labels: waiting for author

**Comment by andreasscherbaum** [comment] 2024-02-04 13:21
> Why support EOL'd versions of Postgres?

I commented on a similar question, but I can't find the answer right now. Here is my opinion on that:

Just because PostgreSQL support is EOL doesn't magically upgrade all databases out there to a version which is supported. Seeing companies - and private users - running on old versions is unfortunately the reality.

While we should not spend an effort to support pg_repack on older versions of PostgreSQL, we should however have advanced warning when and if it stops working on older versions. There is a viable difference between

"pg_repack does no longer officially support PG 9.6, but we haven't seen any problems. It's your own risk"

and

"It is known that pg_repack does no longer work on PG 9.6"

This comes down to having tests running on older versions as well, and once these tests fail, gather that information and update the documentation. And only then stop testing on older versions.
