### ISSUE TITLE
ERROR in regress case: repack_run

### ISSUE THREAD

**Issue by HBKO** [reorg/pg_repack#317] opened 2022-09-09 03:12 UTC
When I run regress case repack_run, it shows errors as follows:

```
  \! pg_repack --dbname=contrib_regression --table=tbl_cluster
  INFO: repacking table "public.tbl_cluster"
  ERROR: query failed: ERROR:  current transaction is aborted, commands ignored until end of transaction block
  DETAIL: query was: RESET statement_timeout
  ERROR:  canceling wait for synchronous replication due to user request
  DETAIL:  The synchronous ddl was canceled.
  \! pg_repack --dbname=contrib_regression --table=tbl_badindex
  INFO: repacking table "public.tbl_badindex"
  ERROR: query failed: ERROR:  current transaction is aborted, commands ignored until end of transaction block
  DETAIL: query was: RESET statement_timeout
  ERROR:  canceling wait for synchronous replication due to user request
  DETAIL:  The synchronous ddl was canceled.
  \! pg_repack --dbname=contrib_regression
  INFO: repacking table "public.tbl_badindex"
  WARNING: skipping invalid index: CREATE UNIQUE INDEX idx_badindex_n ON public.tbl_badindex USING btree (n)
  ERROR: query failed: ERROR:  current transaction is aborted, commands ignored until end of transaction block
  DETAIL: query was: RESET statement_timeout
```

pg_repack version is 1.4.6.
It seems that something is wrong with local statement_timeout in lock_access_share function.
Hope to get your answer.

**Comment by andreasscherbaum** [comment] 2023-04-20 10:38
@HBKO Are you able to reproduce this error? And can you activate statement logging in the database, and attach the full query log (for this session) to this ticket?

**Comment by za-arthur** [comment] 2023-06-30 11:15
Because an answer wasn't provided I'm closing the ticket.
@HBKO  feel free to re-open it.

**Closed by za-arthur** 2023-06-30 11:15 UTC
Labels: waiting for author
