### ISSUE TITLE
ERROR:  unexpected index definition

### ISSUE THREAD

**Issue by oppianmatt** [reorg/pg_repack#174] opened 2018-03-22 11:29 UTC
```
pg_repack -a -U postgres -d postgres -e
LOG: (query) SELECT datname FROM pg_database WHERE datallowconn ORDER BY 1;
INFO: repacking database "pitchup_prod"
LOG: (query) select repack.version(), repack.version_sql()
LOG: (query) SET statement_timeout = 0
LOG: (query) SET search_path = pg_catalog, pg_temp, public
LOG: (query) SET client_min_messages = warning
LOG: (query) SELECT t.*, coalesce(v.tablespace, t.tablespace_orig) as tablespace_dest FROM repack.tables t,  (VALUES (quote_ident($1::text))) as v (tablespace) WHERE pkid IS NOT NULL ORDER BY t.relname, t.schemaname
LOG:    (param:0) = (null)
INFO: repacking table "spatial_ref_sys"
LOG: (query) SELECT pg_try_advisory_lock($1, CAST(-2147483648 + $2::bigint AS integer))
LOG:    (param:0) = 16185446
LOG:    (param:1) = 19486
LOG: (query) BEGIN ISOLATION LEVEL READ COMMITTED
LOG: (query) SET LOCAL statement_timeout = 100
LOG: (query) LOCK TABLE spatial_ref_sys IN ACCESS EXCLUSIVE MODE
LOG: (query) RESET statement_timeout
LOG: (query) SELECT pg_get_indexdef(indexrelid) FROM pg_index WHERE indrelid = $1 AND NOT indisvalid
LOG:    (param:0) = 19486
LOG: (query) SELECT indexrelid, repack.repack_indexdef(indexrelid, indrelid, $2, FALSE)  FROM pg_index WHERE indrelid = $1 AND indisvalid
LOG:    (param:0) = 19486
LOG:    (param:1) = (null)
ERROR: query failed: ERROR:  unexpected index definition: CREATE UNIQUE INDEX spatial_ref_sys_pkey ON public.spatial_ref_sys USING btree (srid) TABLESPACE pg_default
DETAIL: query was: SELECT indexrelid, repack.repack_indexdef(indexrelid, indrelid, $2, FALSE)  FROM pg_index WHERE indrelid = $1 AND indisvalid
LOG: (query) SELECT repack.repack_drop($1, $2)
LOG:    (param:0) = 19486
LOG:    (param:1) = 0
```

Was working previously, don't know what has changed. Looks like it has an issue with the postgis tables.

```
                                          List of installed extensions
        Name        | Version |   Schema   |                             Description
--------------------+---------+------------+---------------------------------------------------------------------
 pg_buffercache     | 1.0     | public     | examine the shared buffer cache
 pg_repack          | 1.4.2   | public     | Reorganize tables in PostgreSQL databases with minimal locks
 pg_stat_statements | 1.2     | public     | track execution statistics of all SQL statements executed
 plpgsql            | 1.0     | pg_catalog | PL/pgSQL procedural language
 postgis            | 2.2.2   | public     | PostGIS geometry, geography, and raster spatial types and functions
 postgis_topology   | 2.2.2   | topology   | PostGIS topology spatial types and functions
(6 rows)
```

postgres 9.4

**Comment by dvarrazzo** [comment] 2018-03-22 12:49
Dupe of #169

**Closed by dvarrazzo** 2018-03-22 12:49 UTC
